@@include('../libs/jquery/dist/jquery.js')
@@include('../libs/bootstrap/dist/js/bootstrap.js')
@@include('../libs/owl.carousel/dist/owl.carousel.js')
@@include('../libs/multilevelpushmenu/jquery.multilevelpushmenu.js')
@@include('../libs/fotorama/fotorama.js')
@@include('../libs/perfect-scrollbar/js/perfect-scrollbar.jquery.js')